services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - network
    volumes:
      - ./data:/app/data
      - ./storage/pw_dump_files:/app/storage/pw_dump_files
      - ./storage/pw_dump_images:/app/storage/pw_dump_images
      # - ./Cache:/app/Cache

  nginx:
    build:
      context: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - network
    volumes:
      - ./storage/pw_dump_files:/app/pw_dump_files
      - ./storage/pw_dump_images:/app/pw_dump_images

  ui:
    build:
      context: ui
    ports:
      - "8501:8501"
    networks:
      - network

networks:
  network:
    driver: bridge
